### ISSUE TITLE
License limitations

### ISSUE THREAD

**Issue by FREEZX** [Xiexe/Xiexes-Unity-Shaders-DEPRECATED-#13]
Hi,
I wanted to express my concern regarding the use of the GPLv3 license for the project and ask if it's possible to have it also available under a different license.
If i make a game using the shaders, the entire source code of my game will also need to be made open-sourced and available under the GPL as well. [Reference](http://gplv3.fsf.org/wiki/index.php/FAQ_Update#You_have_a_GPL.27ed_program_that_I.27d_like_to_link_with_my_code_to_build_a_proprietary_program._Does_the_fact_that_I_link_with_your_program_mean_I_have_to_release_my_program_under_a_GPL-compatible_license.3F)
I don't have any issue with open-sourcing my changes on this shader or any additional work based on it and giving attribution to the original creator, but i do have an issue with open-sourcing my entire game.

**Comment by Xiexe** [comment]
Hi! Sorry for the super late response;

I've just finished rewriting this shader from the ground up to be a lot more editable, organized, and user friendly, and plan to release a version to asset store as a means for people like you, who want to use it for their personal or company pursued projects! 

The Git repo  will stay under GPL3, and any version bought from the Asset Store will be under the Unity Asset Store license which means you'd be free to do whatever you want with it, as far as I'm aware. 

I'll have more info on this soon!

**Comment by FREEZX** [comment]
Thanks for the response @Xiexe, that seems like it would be a good solution to the problem. Looking forward to it.

**Comment by FREEZX** [comment]
@Xiexe I can see this project is now deprecated and the new one is up, again under the GPL, and it already has a pull request. Good job!
Please note that if you merge any pull requests, the contributed code is also licensed under the same GPL, so you won't be able to easily dual-license the project (Sell it on the asset store) as you won't be the sole owner of the code. You would need the permission of all contributors to do so.

**Comment by Xiexe** [comment]
Don't worry, the people doing pull requests are well aware of my intentions. We're close friends.

**Comment by FREEZX** [comment]
Awesome, best of luck with the release!
